# Generated by Django 4.2.7 on 2023-11-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trade',
            table='app_trade',
        ),
    ]
