# Generated by Django 4.2.7 on 2023-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
