# Generated by Django 4.2.7 on 2023-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_trade_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='settle_date',
            field=models.DateField(null=True),
        ),
    ]
