# Generated by Django 4.2.7 on 2023-11-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0002_alter_dividend_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividend',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
    ]
