# Generated by Django 4.2.7 on 2023-11-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_alter_instrument_table'),
        ('dividends', '0004_alter_dividend_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument'),
        ),
    ]
