# Generated by Django 4.2.7 on 2023-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_alter_instrument_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
