# Generated by Django 4.2.7 on 2023-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_alter_instrument_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='company_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='dividend_info_link',
            field=models.URLField(null=True),
        ),
    ]
