# Generated by Django 4.2.7 on 2023-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0004_instrument_company_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='company_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='dividend_info_link',
            field=models.URLField(default=''),
        ),
    ]
