# Generated by Django 4.2.7 on 2023-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0006_instrument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='price_source_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
