# Generated by Django 4.2.7 on 2023-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0007_instrument_price_source_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('code',)},
        ),
    ]
