# Generated by Django 4.2.7 on 2023-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0009_instrument_alt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='dividend_frequency',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='instrument',
            name='sector',
            field=models.CharField(default='', max_length=20),
        ),
    ]
