# Generated by Django 4.2.7 on 2023-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='app_portfolio',
        ),
    ]
