# Generated by Django 4.2.7 on 2023-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
