# Generated by Django 4.2.7 on 2023-11-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrument', '0003_alter_instrument_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ex_div_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument')),
            ],
        ),
    ]
