# Generated by Django 4.2.7 on 2023-11-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DividendSchedule', '0002_alter_dividendschedule_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendschedule',
            name='external_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='dividendschedule',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
