# Generated by Django 4.2.7 on 2023-11-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DividendSchedule', '0003_dividendschedule_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendschedule',
            name='external_link2',
            field=models.URLField(null=True),
        ),
    ]
