# Generated by Django 4.2.7 on 2023-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DividendSchedule', '0006_remove_dividendschedule_company_link_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dividendschedule',
            table='app_dividendschedule',
        ),
    ]
