# Generated by Django 4.2.7 on 2023-11-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DividendSchedule', '0007_alter_dividendschedule_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendschedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
