# Generated by Django 4.2.7 on 2023-11-27 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_source', models.CharField(max_length=20)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_instrument_price',
            },
        ),
    ]
