# Generated by Django 4.2.7 on 2023-11-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0006_instrument_user'),
        ('InstrumentPrice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentprice',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument'),
            preserve_default=False,
        ),
    ]
