# Generated by Django 4.2.7 on 2023-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentPrice', '0002_instrumentprice_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentprice',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
