# Generated by Django 4.2.7 on 2023-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentPrice', '0003_alter_instrumentprice_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentprice',
            name='ma200',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='ma50',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='year_high',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='year_low',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
