# Generated by Django 4.2.7 on 2023-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentPrice', '0005_instrumentprice_currency_instrumentprice_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentprice',
            name='pcnt_from_year_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
